name: Download Artifact, Create Release, and Upload Artifact

on:
  repository_dispatch:
    types: [create-release]

jobs:
  processReleaseAndUploadArtifact:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get Artifact Info
        run: |
          echo "Artifact Name: ${{ github.event.client_payload.artifact_name }}"
          echo "Version: ${{ github.event.client_payload.version }}"
          
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ github.event.client_payload.artifact_name }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          repository: hmarques98/meili-ios
          run-id: ${{ github.event.client_payload.run_id }}
      - name: Create a Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: v${{ github.event.client_payload.version }}
          release_name: v${{ github.event.client_payload.version }} Release
          draft: false
          prerelease: false
          body: "Release for version ${{ github.event.client_payload.version }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
      - name: Upload Artifact to the Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./${{ github.event.client_payload.artifact_name }}
          asset_name: ${{ github.event.client_payload.artifact_name }}
          asset_content_type: application/zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
