name: Handle External Trigger

on:
  repository_dispatch:
    types: [create-release]

jobs:
  createRelease:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      # Add steps to download the artifact from a shared location or directly from the source repo (if possible)

      - name: Create a Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.event.client_payload.tag_name }}
          release_name: Release ${{ github.event.client_payload.release_name }}
          draft: false
          prerelease: false
          body: "Description of the release"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      # Additional step to upload an artifact to the release if necessary
