name: Release

on:
  push:
    tags:
      - 'v*' # Trigger on new tags (e.g., v1.0.0)

jobs:
  release:
    runs-on: macos-latest # Use macOS runner

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Extract Version from Tag
        id: extract_version
        run: echo "::set-output name=version::${GITHUB_REF#refs/tags/v}"

      - name: Update Package.swift
        run: |
          sed -i '' "s|url: \".*\"|url: \"https://github.com/hmarques98/meili-ios/releases/download/${{ steps.extract_version.outputs.version }}/MeiliSDK-${{ steps.extract_version.outputs.version }}.xcframework.zip\"|" Package.swift

          # Download the xcframework zip and calculate checksum
          wget -O MeiliSDK.xcframework.zip https://github.com/hmarques98/meili-ios/releases/download/${{ steps.extract_version.outputs.version }}/MeiliSDK-${{ steps.extract_version.outputs.version }}.xcframework.zip
          checksum=$(swift package compute-checksum MeiliSDK.xcframework.zip)
          sed -i '' "s|checksum: \".*\"|checksum: \"$checksum\"|" Package.swift

      - name: Commit and Push Changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add Package.swift
          git commit -m "Update Package.swift for version ${{ steps.extract_version.outputs.version }}"
          git push origin HEAD:main
